### ISSUE TITLE
ClassCastExcpetion

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-TCFModules#27]
It seems that a requested token from sNodes.get(seq[i]) is not a token, but a SSpan. If this is caused by a data error, please create a better error message. 

Cannot map 'de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.salt.saltCore.impl.SElementIdImpl@e88256d7 
(namespace: graph, name: id, value: salt:/TCF/Freiburg_205_Dep_Fulltext)' with 
module 'TCFImporter', because of a mapping result was 'FAILED'.
An exception was thrown by the mapper threads 
'Thread[TCFImporter_mapper(salt:/TCF/Freiburg_205_Dep_Fulltext),5,TCFImporter_mapperGroup]'. 

de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepper.modules.exceptions.PepperModuleXMLResourceException: 
Cannot read 
xml-file'file:/Users/nicolehmann/Documents/Verhoeven/Register/Annotation/FR-Cor-July/TCF/Freiburg_205_Dep_Fulltext.tcf', 
because of a nested exception.
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperMapperImpl.readXMLResource(PepperMapperImpl.java:310)
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepperModules.tcfModules.TCFMapperImport.mapSDocument(TCFMapperImport.java:94)
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperMapperControllerImpl.map(PepperMapperControllerImpl.java:240)
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:185)
Caused by: java.lang.ClassCastException: de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.sDocumentStructure.impl.SSpanImpl 
cannot be cast to de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.salt.saltCommon.sDocumentStructure.SToken
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepperModules.tcfModules.TCFMapperImport$TCFReader.startElement(TCFMapperImport.java:292)
at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown 
Source)
at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown 
Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown 
Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at de.hu 
http://de.hu_berlin.german.korpling.saltnpepper.pepper.modules.impl.PepperMapperImpl.readXMLResource(PepperMapperImpl.java:295)
... 3 more
--------------------------- pepper job status ---------------------------
id:'fb2fua65
active documents:1 of 4
status:IN_PROGRESS
total progress:75%
processing time:0:00:10.050
salt:/0/TCF/Freiburg_205_Dep_Fulltext(DELETED)                  100%
## salt:/0/TCF/Freiburg_30_Dep_FullText(IN_PROGRESS)                50%

conversion ended successfully, required time: 0:00:15.466 s

**Comment by MartinKl** [comment]
This actually was a data problem, but I improved the code. Now no exception is thrown and the import is aborted, if an id is used by two different entities.
